language: node_js
node_js:
 - "node"
env:
- NODE_ENV=TEST
cache:
  directories:
   - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master